version: '3.1'

services:
  frontend:
    build: 
      context: ./frontend
      args:
        VITE_BACKEND_URL: ${BACKEND_URL}
    depends_on:
      - backend
    ports:
      - 3002:80
    environment:
      VITE_BACKEND_URL: ${BACKEND_URL}
  
  backend:
    build: ./backend
    depends_on:
      - db
    ports:
      - ${PORT}:3000
    environment: 
      PORT: ${PORT}
      MONGO_ADMIN_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_ADMIN_PASSWORD: ${MONGO_ADMIN_PASSWORD}
      MONGO_HOSTNAME: ${MONGO_HOSTNAME}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB_NAME: ${MONGO_DB_NAME}
      JWT_EXPIRY_TIME: ${JWT_EXPIRY_TIME}
      JWT_PRIVATE_KEY: ${JWT_PRIVATE_KEY}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongodata:/data/db
    ports:
      # https://github.com/docker-library/mongo/issues/177#issuecomment-301945353
      - "127.0.0.1:${MONGO_PORT}:27017"


volumes:
  mongodata:

  