version: '3.1'

services:
  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}
    volumes:
      - mongodata:/data/db
    ports:
      # https://github.com/docker-library/mongo/issues/177#issuecomment-301945353
      - "127.0.0.1:${MONGO_PORT}:27017"

volumes:
  mongodata:

  